### ISSUE TITLE
Number of data types in synthetic

### ISSUE THREAD

**Issue by imadhajjar** [jmjos/ratatoskr#26]
in config.xml it's =5 and in the code it's =2.

**Comment by jmjos** [comment]
In synthetic the data type should correspond with the source address.

**Comment by imadhajjar** [comment]
Make each sender choose a random data type between [0, number_of_traffic_types-1].
This solution is hopefully better than making the data type as the id of the sender, which is first no realistic scenario and it results in huge sparse matrices and csv files (can not be loaded easily) which makes debugging harder.
