### ISSUE TITLE
CA-simulator-FlitSize-Doubt

### ISSUE THREAD

**Issue by kiranmai140** [jmjos/ratatoskr#82]
When using synthetic traffic patterns [ Benchmark=synthetic], is there any parameter that specifies the size of the flit? 
To my understanding,
In config.ini->[Config]->flitsPerPacket parameter is passed to the simulator using config.xml input file to specify the length of the packet in flits. So, a packet is divided into a number of flits as specified by the parameter flitsPerPacket. But how can we get the size of the flit that is transmitted. 
Also, when using synthetic traffic patterns [ Benchmark=synthetic], is any raw data being transmitted.
Please help me in understanding the implementation.

Thank you.

**Comment by jmjos** [comment]
Thanks for your interest in our simulator. I hope that we can clarify.

Setting the size of a flit: The bitWidth is set in the config.xml file, line 10. See: (https://github.com/jmjos/ratatoskr/blob/f6f3390371281d9948f618d52c25fd580ddbef57/simulator/config/config.xml#L10 This sets the variable `globalResources::bitWidth` in the simulator. We use it, e.g., to calculate the injection and ejection bandwidth, see https://github.com/jmjos/ratatoskr/blob/f6f3390371281d9948f618d52c25fd580ddbef57/simulator/src/model/networkInterface/NetworkInterfaceVC.cpp#L131

When using synthetic modes, we do not transmit useful payload data. The simulator does generate a correct amount of flits with bitWidth space. We never saw the need to transmit actual payload data for all previous studies. You can extend the simulator easily by adding a payload member variable to the Flit class, see [https://github.com/jmjos/ratatoskr/blob/master/simulator/src/model/traffic/Flit.h
](https://github.com/jmjos/ratatoskr/blob/master/simulator/src/model/traffic/Flit.h
)
I hope that answers the questions.

**Comment by kiranmai140** [comment]
Thank you for the reply.
